export const productList = [
  {
    img: "1.webp",
    price: 10,
    title: "T-Shirt",
    id: 1,
    category: "clothes",
    sex: "men",
    size: "m",
    color: "black",
  },
  {
    img: "1.webp",
    price: 11,
    title: "Shorts",
    id: 2,
    category: "clothes",
    sex: "men",
    size: "m",
    color: "black",
  },
  {
    img: "1.webp",
    price: 12,
    title: "Jeans",
    id: 3,
    category: "clothes",
    sex: "men",
    size: "m",
    color: "black",
  },
  {
    img: "1.webp",
    price: 13,
    title: "Cloak",
    id: 4,
    category: "clothes",
    sex: "men",
    size: "m",
    color: "black",
  },
  {
    img: "1.webp",
    price: 14,
    title: "Hat",
    id: 5,
    category: "clothes",
    sex: "men",
    size: "m",
    color: "black",
  },
  {
    img: "1.webp",
    price: 15,
    title: "Jacket",
    id: 6,
    category: "clothes",
    sex: "men",
    size: "m",
    color: "black",
  },
  {
    img: "1.webp",
    price: 16,
    title: "Shirt",
    id: 7,
    category: "clothes",
    sex: "men",
    size: "m",
    color: "black",
  },
  {
    img: "1.webp",
    price: 17,
    title: "Glasses",
    id: 8,
    category: "clothes",
    sex: "men",
    size: "m",
    color: "black",
  },
];
